// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tutorial.proto
// Protobuf Java Version: 4.27.2

package compiled;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Person people = 1;</code>
   */
  java.util.List<compiled.Person> 
      getPeopleList();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  compiled.Person getPeople(int index);
  /**
   * <code>repeated .Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  java.util.List<? extends compiled.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  compiled.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
